# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Wallace CI - Continuous Integration

on:
  pull_request:  
    branches: 
      - main 

jobs:
  install-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
            
      - run: cd projeto-site
      - run: npm install
          
  build-npm:
    needs: install-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
      
      - run: cd projeto-site
      - run: ls 
      - run: npm run build
  
  deploy:
    needs: build-npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Sync files with S3 bucket
        run: |
          aws s3 sync ./projeto-site s3://http://testesitewallace.s3-website-us-east-1.amazonaws.com --delete
